esphome:
  name: esphome-web-4a9e6c

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

switch:
  - platform: gpio
    pin: D4
    name: "Greenhouse_edd_flow_pump"

binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
    name: "Tomato Float Sensor"
    filters:
      # Small filter, to debounce the switch
      - delayed_on: 100ms
      - delayed_off: 100ms
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
    name: "Autopot Float Sensor"
    filters:
      # Small filter, to debounce the switch
      - delayed_on: 100ms
      - delayed_off: 100ms

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-4A9E6C"
    password: "vsyKwh8yqkPh"

captive_portal:
