esphome:
  name: veranda

esp8266:
  board: d1

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "781f3e098bd72f28e483415833e79691"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Veranda Fallback Hotspot"
    password: "GHHCbwV38mwr"

web_server:
  port: 80
  

captive_portal:

switch:
  - platform: gpio
    pin: D6
    name: "Logstore_lights"
  - platform: gpio
    pin: D7
    name: "Water Butt Pump"

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
    name: "Veranda Motion"
    device_class: motion
  - platform: gpio
    pin:
      number: D15
      mode: INPUT_PULLUP
    name: "Water Butt Float Switch"
  
